export default (window.theme = {
	headerHeight: '4rem',
	sidebarWidth: '16rem',
	perimeterPadding: '1rem',
	fontFamily: 'Helvetica, sans-serif',
	colorBackground: '#014270',
	colorMain: '#CBE4F5',
	colorLink: 'orange',
	colorDark1: '#014270',
	colorDark2: '#427EB3',
	colorDark3: '#CBE4F5',
	colorOnDark1: '#427EB3',
	colorOnDark2: '#CBE4F5',
	colorOnDark3: '#FFFFFF',
});
